# Uncomment the next line to define a global platform for your project
platform :ios, '14.4'

target 'NameThatFlower' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NameThatFlower
  pod 'Alamofire', '~> 4.4'
  pod 'SwiftyJSON'

end
